//Source code generated by AppGPT (www.appgpt.tech)

//Class to create tables and seed new database
import { DataSource } from 'typeorm';
import { DBConfiguration } from './Configuration';
import { SettingsEntity } from './db/Settings.entity';
//autogenerate imports based on resources
import { UsersEntity } from './db/Users.entity';
import { VendorsEntity } from './db/Vendors.entity';
import { CustomersEntity } from './db/Customers.entity';
import { InventoryEntity } from './db/Inventory.entity';
import { ProductsEntity } from './db/Products.entity';
import { ProductCategoriesEntity } from './db/ProductCategories.entity';
import { DiscountsEntity } from './db/Discounts.entity';
import { ShoppingCartEntity } from './db/ShoppingCart.entity';
import { OrdersEntity } from './db/Orders.entity';
import { OrderDetailsEntity } from './db/OrderDetails.entity';
import { PaymentsEntity } from './db/Payments.entity';
import { ReviewsEntity } from './db/Reviews.entity';
import { SupportTicketsEntity } from './db/SupportTickets.entity';

export class Database {
  static dbConfiguration: DBConfiguration;
  public static ds: DataSource;

  static async Initialize(dbConfiguration: DBConfiguration) {
    Database.dbConfiguration = dbConfiguration;
    let dbConfig: any = dbConfiguration as any;
    //Autogenerate entities array from resource names

    dbConfig.entities = [
      SettingsEntity,
      UsersEntity,
      VendorsEntity,
      CustomersEntity,
      InventoryEntity,
      ProductsEntity,
      ProductCategoriesEntity,
      DiscountsEntity,
      ShoppingCartEntity,
      OrdersEntity,
      OrderDetailsEntity,
      PaymentsEntity,
      ReviewsEntity,
      SupportTicketsEntity,
    ];
    Database.ds = new DataSource(dbConfig);
    await Database.ds.initialize();

    //TODO: Drop all tables

    await Database.Seed();
  }
  static async Seed() {
    let data: any = {
      Users: [
        {
          username: 'username 1',
          email: 'email 1',
          password: 'password 1',
          role: 'role 1',
          id: 53,
        },
        {
          username: 'username 2',
          email: 'email 2',
          password: 'password 2',
          role: 'role 2',
          id: 37,
        },
        {
          username: 'username 3',
          email: 'email 3',
          password: 'password 3',
          role: 'role 3',
          id: 98,
        },
        {
          username: 'username 4',
          email: 'email 4',
          password: 'password 4',
          role: 'role 4',
          id: 50,
        },
        {
          username: 'username 5',
          email: 'email 5',
          password: 'password 5',
          role: 'role 5',
          id: 5,
        },
      ],
      Vendors: [
        {
          companyName: 'companyName 1',
          contactName: 'contactName 1',
          email: 'email 1',
          password: 'password 1',
          id: 63,
        },
        {
          companyName: 'companyName 2',
          contactName: 'contactName 2',
          email: 'email 2',
          password: 'password 2',
          id: 98,
        },
        {
          companyName: 'companyName 3',
          contactName: 'contactName 3',
          email: 'email 3',
          password: 'password 3',
          id: 2,
        },
        {
          companyName: 'companyName 4',
          contactName: 'contactName 4',
          email: 'email 4',
          password: 'password 4',
          id: 96,
        },
        {
          companyName: 'companyName 5',
          contactName: 'contactName 5',
          email: 'email 5',
          password: 'password 5',
          id: 46,
        },
      ],
      Customers: [
        {
          customerName: 'customerName 1',
          email: 'email 1',
          password: 'password 1',
          billingAddress: 'billingAddress 1',
          shippingAddress: 'shippingAddress 1',
          country: 'country 1',
          phone: 'phone 1',
          id: 2,
        },
        {
          customerName: 'customerName 2',
          email: 'email 2',
          password: 'password 2',
          billingAddress: 'billingAddress 2',
          shippingAddress: 'shippingAddress 2',
          country: 'country 2',
          phone: 'phone 2',
          id: 37,
        },
        {
          customerName: 'customerName 3',
          email: 'email 3',
          password: 'password 3',
          billingAddress: 'billingAddress 3',
          shippingAddress: 'shippingAddress 3',
          country: 'country 3',
          phone: 'phone 3',
          id: 27,
        },
        {
          customerName: 'customerName 4',
          email: 'email 4',
          password: 'password 4',
          billingAddress: 'billingAddress 4',
          shippingAddress: 'shippingAddress 4',
          country: 'country 4',
          phone: 'phone 4',
          id: 10,
        },
        {
          customerName: 'customerName 5',
          email: 'email 5',
          password: 'password 5',
          billingAddress: 'billingAddress 5',
          shippingAddress: 'shippingAddress 5',
          country: 'country 5',
          phone: 'phone 5',
          id: 31,
        },
      ],
      Inventory: [
        { product: 1, quantity: 1, lowStockThreshold: 1, id: 39 },
        { product: 2, quantity: 2, lowStockThreshold: 2, id: 17 },
        { product: 3, quantity: 3, lowStockThreshold: 3, id: 87 },
        { product: 4, quantity: 4, lowStockThreshold: 4, id: 13 },
        { product: 5, quantity: 5, lowStockThreshold: 5, id: 81 },
      ],
      Products: [
        {
          productName: 'productName 1',
          vendor: 1,
          price: 0.59,
          weight: 0.12,
          description: 'description 1',
          thumbnail: 'thumbnail 1',
          image: 'image 1',
          category: 1,
          creationDate: '2025-01-16T11:27:48.676Z',
          stock: 1,
          id: 64,
        },
        {
          productName: 'productName 2',
          vendor: 2,
          price: 0.96,
          weight: 0.48,
          description: 'description 2',
          thumbnail: 'thumbnail 2',
          image: 'image 2',
          category: 2,
          creationDate: '2024-02-29T01:57:50.831Z',
          stock: 2,
          id: 65,
        },
        {
          productName: 'productName 3',
          vendor: 3,
          price: 0.68,
          weight: 0.06,
          description: 'description 3',
          thumbnail: 'thumbnail 3',
          image: 'image 3',
          category: 3,
          creationDate: '2023-06-18T21:05:07.343Z',
          stock: 3,
          id: 60,
        },
        {
          productName: 'productName 4',
          vendor: 4,
          price: 1,
          weight: 0.14,
          description: 'description 4',
          thumbnail: 'thumbnail 4',
          image: 'image 4',
          category: 4,
          creationDate: '2023-05-12T01:13:33.625Z',
          stock: 4,
          id: 39,
        },
        {
          productName: 'productName 5',
          vendor: 5,
          price: 0.06,
          weight: 0.99,
          description: 'description 5',
          thumbnail: 'thumbnail 5',
          image: 'image 5',
          category: 5,
          creationDate: '2024-05-19T21:12:51.884Z',
          stock: 5,
          id: 93,
        },
      ],
      ProductCategories: [
        { category: 'category 1', id: 64 },
        { category: 'category 2', id: 24 },
        { category: 'category 3', id: 37 },
        { category: 'category 4', id: 71 },
        { category: 'category 5', id: 59 },
      ],
      Discounts: [
        {
          product: 1,
          discountType: 'discountType 1',
          description: 'description 1',
          discountAmount: 0.2,
          discountPercent: 0.18,
          id: 0,
        },
        {
          product: 2,
          discountType: 'discountType 2',
          description: 'description 2',
          discountAmount: 0.51,
          discountPercent: 0,
          id: 21,
        },
        {
          product: 3,
          discountType: 'discountType 3',
          description: 'description 3',
          discountAmount: 0.39,
          discountPercent: 0.19,
          id: 92,
        },
        {
          product: 4,
          discountType: 'discountType 4',
          description: 'description 4',
          discountAmount: 0.82,
          discountPercent: 0.56,
          id: 98,
        },
        {
          product: 5,
          discountType: 'discountType 5',
          description: 'description 5',
          discountAmount: 0.3,
          discountPercent: 0.81,
          id: 90,
        },
      ],
      ShoppingCart: [
        { customer: 1, product: 1, priceAtPurchase: 0.32, quantity: 1, id: 13 },
        { customer: 2, product: 2, priceAtPurchase: 0.41, quantity: 2, id: 48 },
        { customer: 3, product: 3, priceAtPurchase: 0.64, quantity: 3, id: 75 },
        { customer: 4, product: 4, priceAtPurchase: 0.4, quantity: 4, id: 24 },
        { customer: 5, product: 5, priceAtPurchase: 0.28, quantity: 5, id: 15 },
      ],
      Orders: [
        {
          orderNumber: 'orderNumber 1',
          customer: 1,
          totalAmount: 0.14,
          vat: 0.68,
          totalAmountWithVat: 0.23,
          shippingCost: 0.51,
          shippingAddress: 'shippingAddress 1',
          orderAddress: 'orderAddress 1',
          orderEmail: 'orderEmail 1',
          orderDate: '2024-12-20T08:25:48.646Z',
          orderStatus: 'orderStatus 1',
          trackingNo: 'trackingNo 1',
          id: 80,
        },
        {
          orderNumber: 'orderNumber 2',
          customer: 2,
          totalAmount: 0.76,
          vat: 0.37,
          totalAmountWithVat: 0.06,
          shippingCost: 0.92,
          shippingAddress: 'shippingAddress 2',
          orderAddress: 'orderAddress 2',
          orderEmail: 'orderEmail 2',
          orderDate: '2024-08-06T16:53:46.630Z',
          orderStatus: 'orderStatus 2',
          trackingNo: 'trackingNo 2',
          id: 33,
        },
        {
          orderNumber: 'orderNumber 3',
          customer: 3,
          totalAmount: 0.47,
          vat: 0.93,
          totalAmountWithVat: 0.61,
          shippingCost: 0.98,
          shippingAddress: 'shippingAddress 3',
          orderAddress: 'orderAddress 3',
          orderEmail: 'orderEmail 3',
          orderDate: '2023-05-01T07:32:50.254Z',
          orderStatus: 'orderStatus 3',
          trackingNo: 'trackingNo 3',
          id: 92,
        },
        {
          orderNumber: 'orderNumber 4',
          customer: 4,
          totalAmount: 0.75,
          vat: 0.54,
          totalAmountWithVat: 0.76,
          shippingCost: 0.32,
          shippingAddress: 'shippingAddress 4',
          orderAddress: 'orderAddress 4',
          orderEmail: 'orderEmail 4',
          orderDate: '2023-08-27T15:34:50.233Z',
          orderStatus: 'orderStatus 4',
          trackingNo: 'trackingNo 4',
          id: 54,
        },
        {
          orderNumber: 'orderNumber 5',
          customer: 5,
          totalAmount: 0.33,
          vat: 0.42,
          totalAmountWithVat: 0.1,
          shippingCost: 0.2,
          shippingAddress: 'shippingAddress 5',
          orderAddress: 'orderAddress 5',
          orderEmail: 'orderEmail 5',
          orderDate: '2024-06-28T11:52:36.372Z',
          orderStatus: 'orderStatus 5',
          trackingNo: 'trackingNo 5',
          id: 17,
        },
      ],
      OrderDetails: [
        {
          orderNumber: 1,
          line: 1,
          product: 1,
          price: 0.48,
          quantity: 1,
          id: 1,
        },
        {
          orderNumber: 2,
          line: 2,
          product: 2,
          price: 0.27,
          quantity: 2,
          id: 35,
        },
        {
          orderNumber: 3,
          line: 3,
          product: 3,
          price: 0.48,
          quantity: 3,
          id: 84,
        },
        { orderNumber: 4, line: 4, product: 4, price: 0, quantity: 4, id: 18 },
        { orderNumber: 5, line: 5, product: 5, price: 0, quantity: 5, id: 42 },
      ],
      Payments: [
        {
          orderNumber: 1,
          amount: 0.01,
          paymentMethod: 'paymentMethod 1',
          paymentDate: '2023-11-27T16:40:00.220Z',
          paymentStatus: 'paymentStatus 1',
          id: 75,
        },
        {
          orderNumber: 2,
          amount: 0.86,
          paymentMethod: 'paymentMethod 2',
          paymentDate: '2025-02-04T22:39:39.437Z',
          paymentStatus: 'paymentStatus 2',
          id: 37,
        },
        {
          orderNumber: 3,
          amount: 0.37,
          paymentMethod: 'paymentMethod 3',
          paymentDate: '2024-05-07T23:55:14.449Z',
          paymentStatus: 'paymentStatus 3',
          id: 65,
        },
        {
          orderNumber: 4,
          amount: 0.39,
          paymentMethod: 'paymentMethod 4',
          paymentDate: '2023-05-18T00:21:48.257Z',
          paymentStatus: 'paymentStatus 4',
          id: 2,
        },
        {
          orderNumber: 5,
          amount: 0.52,
          paymentMethod: 'paymentMethod 5',
          paymentDate: '2024-01-13T00:14:23.952Z',
          paymentStatus: 'paymentStatus 5',
          id: 44,
        },
      ],
      Reviews: [
        {
          product: 1,
          customer: 1,
          vendor: 1,
          rating: 0.24,
          reviewDetails: 'reviewDetails 1',
          date: '2024-05-23T20:01:36.887Z',
          id: 33,
        },
        {
          product: 2,
          customer: 2,
          vendor: 2,
          rating: 0.73,
          reviewDetails: 'reviewDetails 2',
          date: '2023-09-28T19:36:01.191Z',
          id: 10,
        },
        {
          product: 3,
          customer: 3,
          vendor: 3,
          rating: 0.59,
          reviewDetails: 'reviewDetails 3',
          date: '2024-09-11T15:42:10.002Z',
          id: 75,
        },
        {
          product: 4,
          customer: 4,
          vendor: 4,
          rating: 0.68,
          reviewDetails: 'reviewDetails 4',
          date: '2024-11-05T00:11:14.197Z',
          id: 55,
        },
        {
          product: 5,
          customer: 5,
          vendor: 5,
          rating: 0.54,
          reviewDetails: 'reviewDetails 5',
          date: '2023-09-12T12:24:41.289Z',
          id: 27,
        },
      ],
      SupportTickets: [
        {
          user: 1,
          customer: 1,
          description: 'description 1',
          status: 'status 1',
          creationDate: '2024-07-11T12:34:34.190Z',
          resolutionDate: '2024-08-10T13:48:17.542Z',
          id: 77,
        },
        {
          user: 2,
          customer: 2,
          description: 'description 2',
          status: 'status 2',
          creationDate: '2024-07-30T12:58:15.501Z',
          resolutionDate: '2024-07-25T18:48:00.592Z',
          id: 92,
        },
        {
          user: 3,
          customer: 3,
          description: 'description 3',
          status: 'status 3',
          creationDate: '2023-11-01T01:23:35.921Z',
          resolutionDate: '2025-01-14T01:08:36.177Z',
          id: 12,
        },
        {
          user: 4,
          customer: 4,
          description: 'description 4',
          status: 'status 4',
          creationDate: '2024-11-06T10:55:21.726Z',
          resolutionDate: '2023-04-28T19:55:23.209Z',
          id: 60,
        },
        {
          user: 5,
          customer: 5,
          description: 'description 5',
          status: 'status 5',
          creationDate: '2024-02-27T07:58:29.226Z',
          resolutionDate: '2024-07-27T08:40:03.278Z',
          id: 25,
        },
      ],
    };
    //Autogenerate multiple such calls ie for each resource and its data object
    let isSeeded = await this.IsSeeded();
    //if (!isSeeded) {
    //forcing app recreation
    if (true) {
      console.log('   Seeding database...');
      await this.SeedResource('UsersEntity', data.Users);
      await this.SeedResource('VendorsEntity', data.Vendors);
      await this.SeedResource('CustomersEntity', data.Customers);
      await this.SeedResource('InventoryEntity', data.Inventory);
      await this.SeedResource('ProductsEntity', data.Products);
      await this.SeedResource(
        'ProductCategoriesEntity',
        data.ProductCategories,
      );
      await this.SeedResource('DiscountsEntity', data.Discounts);
      await this.SeedResource('ShoppingCartEntity', data.ShoppingCart);
      await this.SeedResource('OrdersEntity', data.Orders);
      await this.SeedResource('OrderDetailsEntity', data.OrderDetails);
      await this.SeedResource('PaymentsEntity', data.Payments);
      await this.SeedResource('ReviewsEntity', data.Reviews);
      await this.SeedResource('SupportTicketsEntity', data.SupportTickets);
      await this.SeedResource('SettingsEntity', {
        settingname: 'isSeeded',
        settingvalue: 'true',
      });
    } else {
      console.log('   Database seeded already!');
    }
  }
  static async IsSeeded() {
    const repo = Database.ds.getRepository('SettingsEntity');
    let rec: any = await repo.findOne({
      select: {
        settingname: true,
        settingvalue: true,
      },
      where: {
        settingname: 'isSeeded',
      },
    });
    if (rec && rec.settingvalue) return true;
    return false;
  }
  static async SeedResource(resourceName: any, resourceData: any) {
    const repo = Database.ds.getRepository(resourceName);
    //await repo.clear();
    console.log('   Seeding table ' + resourceName);
    await repo.upsert(resourceData, ['id']);
  }
}
